apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
type: Opaque
stringData:
  username: "guest"
  password: "guest"
  uri: "amqp://guest:guest@rabbitmq:5672/"
---
apiVersion: v1
kind: Secret
metadata:
  name: stripe-secrets
type: Opaque
stringData:
  stripe-secret-key: "sk_test_51RU2CMPQyeZEQbOIwbvZGKy6jX9Ke699GeOgr7lJP7Av8ZmFt8PelI9xZfw1RpiUfXhKjkA4WcKZSlaESmZqUzxJ00o0DE9Iky"
  stripe-webhook-key: "whsec_4a65cfde05bb8714b6f54ad39b6bca295d385a4d0cd7e3423a614e8bf0d974cb"
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-credentials
type: Opaque
stringData:
  uri: "mongodb://192.168.49.1:27017"
